/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.digitalpersona.uareu.*;
import com.umg.controlador.ControladorRegistrarEmpleado;
import com.umg.implementacion.PuestoImp;
import com.umg.modelos.ModeloPuesto;
import com.umg.modelos.ModeloVistaRegistrarEmpleado;
import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author axels
 */
public class VistaRegistrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form VistaRegistrarEmpleado
     */

    private Reader reader;

    public VistaRegistrarEmpleado() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        reader = obtenerReader();
        cargarPuestos();
        ModeloVistaRegistrarEmpleado modelo = new ModeloVistaRegistrarEmpleado(this);
        ControladorRegistrarEmpleado controlador = new ControladorRegistrarEmpleado(modelo);
        setControlador(controlador);
        controlador.cargarPuestos(cbPuesto);
        controlador.cargarJefes(cbJefeInmediato);
    }

    public void cargarPuestos() {
        PuestoImp puesto = new PuestoImp();
        List<ModeloPuesto> puestos = puesto.obtenerPuestos();
        cbPuesto.removeAllItems(); // Limpia si ya tenía datos


        for (ModeloPuesto p : puestos) {
            cbPuesto.addItem(String.valueOf(p));
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        panelOpciones1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        panelInfoPersonal1 = new javax.swing.JPanel();
        txtNom1 = new javax.swing.JTextField();
        txtNom2 = new javax.swing.JTextField();
        txtNom3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtApe1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtApe2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtApeC = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        txtCorreo = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        cbSexo = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblErrorFechaNacimiento = new javax.swing.JLabel();
        lblError2doApellido = new javax.swing.JLabel();
        lblError1erApellido = new javax.swing.JLabel();
        lblError1erApellido1 = new javax.swing.JLabel();
        lblError1erTel = new javax.swing.JLabel();
        lblErrorPrimerNombre = new javax.swing.JLabel();
        lblErrorDpi = new javax.swing.JLabel();
        lblErrorEstado = new javax.swing.JLabel();
        lblErrorSexo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbDepto = new javax.swing.JComboBox<>();
        cbMun = new javax.swing.JComboBox<>();
        txtAldea = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblErrorDepartamento = new javax.swing.JLabel();
        lblErrorMunicipio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtHoraEntrada = new javax.swing.JTextField();
        cbJefeInmediato = new javax.swing.JComboBox<>();
        cbPuesto = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        lblErrorpuesto = new javax.swing.JLabel();
        lblErrorJefe = new javax.swing.JLabel();
        lblErrorHorarioEntrada = new javax.swing.JLabel();
        lblErrorHorarioSalida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelH1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panelH2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        panelH3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        panelH4 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnRegistrarEmpleado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1230, 720));
        setPreferredSize(new java.awt.Dimension(1230, 720));

        jPanel1.setMinimumSize(new java.awt.Dimension(1210, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1226, 720));

        jPanel4.setMinimumSize(new java.awt.Dimension(1220, 720));
        jPanel4.setPreferredSize(new java.awt.Dimension(1220, 1530));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        panelOpciones1.setBackground(new java.awt.Color(240, 253, 244));
        panelOpciones1.setMinimumSize(new java.awt.Dimension(1220, 720));
        panelOpciones1.setPreferredSize(new java.awt.Dimension(1220, 1530));
        panelOpciones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 127, 75));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Registrar Empleado");
        panelOpciones1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        panelInfoPersonal1.setBackground(new java.awt.Color(240, 253, 244));
        panelInfoPersonal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNom1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNom1.setForeground(new java.awt.Color(26, 75, 54));
        txtNom1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNom1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 270, -1));

        txtNom2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNom2.setForeground(new java.awt.Color(26, 75, 54));
        txtNom2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNom2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 270, -1));

        txtNom3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNom3.setForeground(new java.awt.Color(26, 75, 54));
        txtNom3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNom3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtNom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 270, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 127, 75));
        jLabel27.setText("Tercer Nombre");
        panelInfoPersonal1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 90, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 127, 75));
        jLabel28.setText("Primer Nombre*");
        panelInfoPersonal1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 127, 75));
        jLabel29.setText("Segundo Nombre");
        panelInfoPersonal1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 127, 75));
        jLabel30.setText("Primer Apellido*");
        panelInfoPersonal1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, -1));

        txtApe1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtApe1.setForeground(new java.awt.Color(26, 75, 54));
        txtApe1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApe1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtApe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 127, 75));
        jLabel31.setText("Segundo Apellido*");
        panelInfoPersonal1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 110, -1));

        txtApe2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtApe2.setForeground(new java.awt.Color(26, 75, 54));
        txtApe2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApe2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtApe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 270, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 127, 75));
        jLabel32.setText("Apellido de Casada");
        panelInfoPersonal1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 110, -1));

        txtApeC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtApeC.setForeground(new java.awt.Color(26, 75, 54));
        txtApeC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApeC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtApeC, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 270, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 127, 75));
        jLabel33.setText("Fecha de Nacimiento*");
        panelInfoPersonal1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, -1));

        txtFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(26, 75, 54));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 127, 75));
        jLabel34.setText("Estado Civil *");
        panelInfoPersonal1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 127, 75));
        jLabel35.setText("DPI*");
        panelInfoPersonal1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, -1));

        txtDPI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDPI.setForeground(new java.awt.Color(26, 75, 54));
        txtDPI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDPI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 270, -1));

        cbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbEstadoCivil.setForeground(new java.awt.Color(26, 75, 54));
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Estado Civil", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a", "Unión de Hecho" }));
        cbEstadoCivil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(cbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 270, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(26, 75, 54));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 270, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 127, 75));
        jLabel37.setText("Correo Electronico");
        panelInfoPersonal1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 127, 75));
        jLabel36.setText("Número de Teléfono 1*");
        panelInfoPersonal1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        txtNum1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(26, 75, 54));
        txtNum1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNum1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 270, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 127, 75));
        jLabel39.setText("Número de Teléfono 2");
        panelInfoPersonal1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        txtNum2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNum2.setForeground(new java.awt.Color(26, 75, 54));
        txtNum2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNum2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 270, -1));

        cbSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbSexo.setForeground(new java.awt.Color(26, 75, 54));
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Sexo", "Masculino", "Femenino" }));
        cbSexo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        panelInfoPersonal1.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 270, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 127, 75));
        jLabel40.setText("Sexo*");
        panelInfoPersonal1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 40, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 127, 75));
        jLabel19.setText("DATOS GENERALES");
        panelInfoPersonal1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblErrorFechaNacimiento.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblErrorFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, 20));

        lblError2doApellido.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblError2doApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 160, 20));

        lblError1erApellido.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblError1erApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, 20));

        lblError1erApellido1.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblError1erApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, 20));

        lblError1erTel.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblError1erTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 120, 20));

        lblErrorPrimerNombre.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblErrorPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, 20));

        lblErrorDpi.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblErrorDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 170, 20));

        lblErrorEstado.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblErrorEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, 20));

        lblErrorSexo.setForeground(new java.awt.Color(153, 0, 0));
        panelInfoPersonal1.add(lblErrorSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 170, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-cuadro-datospersonales.png"))); // NOI18N
        panelInfoPersonal1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 400));

        panelOpciones1.add(panelInfoPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 970, 400));

        jPanel6.setBackground(new java.awt.Color(240, 253, 244));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 127, 75));
        jLabel14.setText("DIRECCION");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 127, 75));
        jLabel15.setText("Departamento*");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 127, 75));
        jLabel16.setText("Municipio*");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 127, 75));
        jLabel17.setText("Aldea o Colonia");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 127, 75));
        jLabel18.setText("Dirección de Vivienda");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cbDepto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbDepto.setForeground(new java.awt.Color(26, 75, 54));
        cbDepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Departamento", "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso", "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa", "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez", "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa" }));
        cbDepto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(cbDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 270, -1));

        cbMun.setBackground(new java.awt.Color(255, 255, 255));
        cbMun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMun.setForeground(new java.awt.Color(26, 75, 54));
        cbMun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Municipio" }));
        cbMun.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(cbMun, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 270, -1));

        txtAldea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAldea.setForeground(new java.awt.Color(26, 75, 54));
        txtAldea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAldea.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtAldea, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 270, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(26, 75, 54));
        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel6.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, -1));

        lblErrorDepartamento.setForeground(new java.awt.Color(153, 0, 0));
        jPanel6.add(lblErrorDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, 20));

        lblErrorMunicipio.setForeground(new java.awt.Color(153, 0, 0));
        jPanel6.add(lblErrorMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 170, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-cuadro-direccion.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 230));

        panelOpciones1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 970, 230));

        jPanel7.setBackground(new java.awt.Color(240, 253, 244));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 127, 75));
        jLabel20.setText("HORARIO Y PUESTO");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 127, 75));
        jLabel21.setText("Hora de Entrada");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, -1));

        txtHoraEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHoraEntrada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(txtHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, -1));

        cbJefeInmediato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbJefeInmediato.setForeground(new java.awt.Color(26, 75, 54));
        cbJefeInmediato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Jefe Inmediato" }));
        cbJefeInmediato.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(cbJefeInmediato, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 270, -1));

        cbPuesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbPuesto.setForeground(new java.awt.Color(26, 75, 54));
        cbPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Puesto" }));
        cbPuesto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(cbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 270, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 127, 75));
        jLabel38.setText("Puesto*");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 127, 75));
        jLabel41.setText("Jefe Inmediato");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        txtHoraSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHoraSalida.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel7.add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 270, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 127, 75));
        jLabel42.setText("Hora de Salida");
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 100, -1));

        lblErrorpuesto.setForeground(new java.awt.Color(153, 0, 0));
        jPanel7.add(lblErrorpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 20));

        lblErrorJefe.setForeground(new java.awt.Color(153, 0, 0));
        jPanel7.add(lblErrorJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, 20));

        lblErrorHorarioEntrada.setForeground(new java.awt.Color(153, 0, 0));
        jPanel7.add(lblErrorHorarioEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 20));

        lblErrorHorarioSalida.setForeground(new java.awt.Color(153, 0, 0));
        jPanel7.add(lblErrorHorarioSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 170, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-cuadro-direccion.png"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 230));

        panelOpciones1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 760, 970, 230));

        jPanel2.setBackground(new java.awt.Color(240, 253, 244));

        jLabel4.setForeground(new java.awt.Color(240, 253, 244));
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        panelOpciones1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 980, -1, 20));

        jPanel3.setBackground(new java.awt.Color(240, 253, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 127, 75));
        jLabel22.setText("HUELLAS");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        panelH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelH1Layout = new javax.swing.GroupLayout(panelH1);
        panelH1.setLayout(panelH1Layout);
        panelH1Layout.setHorizontalGroup(
            panelH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelH1Layout.setVerticalGroup(
            panelH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel3.add(panelH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 210));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 127, 75));
        jLabel23.setText("Huella 1");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, -1));

        panelH2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelH2Layout = new javax.swing.GroupLayout(panelH2);
        panelH2.setLayout(panelH2Layout);
        panelH2Layout.setHorizontalGroup(
            panelH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelH2Layout.setVerticalGroup(
            panelH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel3.add(panelH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, 210));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 127, 75));
        jLabel24.setText("Huella 2");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, -1));

        panelH3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelH3Layout = new javax.swing.GroupLayout(panelH3);
        panelH3.setLayout(panelH3Layout);
        panelH3Layout.setHorizontalGroup(
            panelH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelH3Layout.setVerticalGroup(
            panelH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel3.add(panelH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 180, 210));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 127, 75));
        jLabel25.setText("Huella 3");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 100, -1));

        panelH4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelH4Layout = new javax.swing.GroupLayout(panelH4);
        panelH4.setLayout(panelH4Layout);
        panelH4Layout.setHorizontalGroup(
            panelH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelH4Layout.setVerticalGroup(
            panelH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel3.add(panelH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 180, 210));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 127, 75));
        jLabel43.setText("Huella 4");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 100, -1));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(0, 127, 75));
        btnRegistrarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registrar Empleado");
        btnRegistrarEmpleado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jPanel3.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 160, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-cuadro-huellas.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 430));

        panelOpciones1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1040, 970, 430));

        jPanel4.add(panelOpciones1);

        jScrollPane1.setViewportView(jPanel4);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnRegistrarEmpleado;
    public javax.swing.JComboBox<String> cbDepto;
    public javax.swing.JComboBox<String> cbEstadoCivil;
    public javax.swing.JComboBox<Object> cbJefeInmediato;
    public javax.swing.JComboBox<String> cbMun;
    public javax.swing.JComboBox<Object> cbPuesto;
    public javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblError1erApellido;
    public javax.swing.JLabel lblError1erApellido1;
    public javax.swing.JLabel lblError1erTel;
    public javax.swing.JLabel lblError2doApellido;
    public javax.swing.JLabel lblErrorDepartamento;
    public javax.swing.JLabel lblErrorDpi;
    public javax.swing.JLabel lblErrorEstado;
    public javax.swing.JLabel lblErrorFechaNacimiento;
    public javax.swing.JLabel lblErrorHorarioEntrada;
    public javax.swing.JLabel lblErrorHorarioSalida;
    public javax.swing.JLabel lblErrorJefe;
    public javax.swing.JLabel lblErrorMunicipio;
    public javax.swing.JLabel lblErrorPrimerNombre;
    public javax.swing.JLabel lblErrorSexo;
    public javax.swing.JLabel lblErrorpuesto;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JPanel panelH1;
    public javax.swing.JPanel panelH2;
    public javax.swing.JPanel panelH3;
    public javax.swing.JPanel panelH4;
    private javax.swing.JPanel panelInfoPersonal1;
    public javax.swing.JPanel panelOpciones1;
    public javax.swing.JTextField txtAldea;
    public javax.swing.JTextField txtApe1;
    public javax.swing.JTextField txtApe2;
    public javax.swing.JTextField txtApeC;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDPI;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtHoraEntrada;
    public javax.swing.JTextField txtHoraSalida;
    public javax.swing.JTextField txtNom1;
    public javax.swing.JTextField txtNom2;
    public javax.swing.JTextField txtNom3;
    public javax.swing.JTextField txtNum1;
    public javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorRegistrarEmpleado controlador){
        btnRegistrarEmpleado.addMouseListener(controlador);
        cbDepto.addActionListener(controlador);
        panelH1.addMouseListener(controlador);
        panelH2.addMouseListener(controlador);
        panelH3.addMouseListener(controlador);
        panelH4.addMouseListener(controlador);
    }

    public Reader obtenerReader() {
        Reader reader = null;
        try {
            ReaderCollection readers = UareUGlobal.GetReaderCollection();
            readers.GetReaders(); // Refrescar la lista de dispositivos conectados
            if (readers.size() == 0) {
                System.out.println("❌ No se detectaron lectores de huella.");
                return null;
            }

            reader = readers.get(0); // Selecciona automáticamente el primer lector encontrado
            System.out.println("✅ Lector seleccionado automáticamente: " + reader.GetDescription().name);

        } catch (UareUException e) {
            System.err.println("❌ Error inicializando el lector: " + e.getMessage());
        }
        return reader;
    }

}
