/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMostrarEmpleado;
import com.umg.modelos.ModeloVistaMostrarEmpleado;

/**
 *
 * @author axels
 */
public class VistaMostrarEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form VistaMostrarEmpleados
     */
    public VistaMostrarEmpleados() {
        initComponents();
        ModeloVistaMostrarEmpleado modelo = new ModeloVistaMostrarEmpleado(this);
        ControladorMostrarEmpleado controlador = new ControladorMostrarEmpleado(modelo);
        setControlador(controlador);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDPI = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btnBuscarEmpleado = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelInfoPersonal1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelTabla = new javax.swing.JPanel();
        lblFondo1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1230, 720));

        fondo.setBackground(new java.awt.Color(240, 253, 244));
        fondo.setMinimumSize(new java.awt.Dimension(1230, 720));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 127, 75));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleados");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 400, 60));

        jPanel2.setBackground(new java.awt.Color(240, 253, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDPI.setBackground(new java.awt.Color(255, 255, 255));
        txtDPI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDPI.setForeground(new java.awt.Color(26, 75, 54));
        txtDPI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDPI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 270, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 127, 75));
        jLabel35.setText("DPI*");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, -1));

        btnBuscarEmpleado.setBackground(new java.awt.Color(0, 127, 75));
        btnBuscarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Buscar Empleado");
        btnBuscarEmpleado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel2.add(btnBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-datos-usuarios.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 190));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 970, 190));

        panelInfoPersonal1.setBackground(new java.awt.Color(240, 253, 244));
        panelInfoPersonal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 127, 75));
        jLabel19.setText("DATOS GENERALES");
        panelInfoPersonal1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        panelTabla.setLayout(new javax.swing.BoxLayout(panelTabla, javax.swing.BoxLayout.X_AXIS));
        jScrollPane1.setViewportView(panelTabla);

        panelInfoPersonal1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 870, 280));

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-cuadro-datospersonales.png"))); // NOI18N
        panelInfoPersonal1.add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 400));

        fondo.add(panelInfoPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 970, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnBuscarEmpleado;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JPanel panelInfoPersonal1;
    public javax.swing.JPanel panelTabla;
    public javax.swing.JTextField txtDPI;
    // End of variables declaration//GEN-END:variables
    private void setControlador(ControladorMostrarEmpleado controlador) {
        btnBuscarEmpleado.addMouseListener(controlador);
    }
}
