/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorUsuario;
import com.umg.modelos.ModeloUsuario;

/**
 *
 * @author axels
 */
public class VistaMantenimientoUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form VistaMantenimeintoUsuarios
     */
    public VistaMantenimientoUsuarios() {
        initComponents();
        ModeloUsuario modelo = new ModeloUsuario(this);
        ControladorUsuario controlador = new ControladorUsuario(modelo);
        setControlador(controlador);
        this.lblErrorContra.setVisible(false);
        this.lblErrorContraVa.setVisible(false);
        this.lblErrorContraVa1.setVisible(false);
        this.lblErrorUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPasswordMantConf = new javax.swing.JPasswordField();
        txtUsuarioMant = new javax.swing.JTextField();
        txtPasswordMant = new javax.swing.JPasswordField();
        btnAgregarUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblErrorContraVa1 = new javax.swing.JLabel();
        lblErrorUsuario = new javax.swing.JLabel();
        lblErrorContraVa = new javax.swing.JLabel();
        lblErrorContra = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEliminarUsuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuarioBus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPasswordMantConfAc = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtPasswordMantAc = new javax.swing.JPasswordField();
        fondoImagen = new javax.swing.JLabel();
        btnActualizarUsuario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        fondo.setBackground(new java.awt.Color(240, 253, 244));
        fondo.setMinimumSize(new java.awt.Dimension(1230, 720));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 127, 75));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Usuarios");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 400, 60));

        jPanel2.setBackground(new java.awt.Color(240, 253, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 127, 75));
        jLabel2.setText("Usuario*");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 127, 76));
        jLabel3.setText("Contraseña*");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 127, 76));
        jLabel12.setText("Confirmar Contraseña*");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        txtPasswordMantConf.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMantConf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordMantConf.setForeground(new java.awt.Color(26, 75, 54));
        txtPasswordMantConf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordMantConf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtPasswordMantConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 270, -1));

        txtUsuarioMant.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioMant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsuarioMant.setForeground(new java.awt.Color(26, 75, 54));
        txtUsuarioMant.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuarioMant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtUsuarioMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 270, -1));

        txtPasswordMant.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordMant.setForeground(new java.awt.Color(26, 75, 54));
        txtPasswordMant.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordMant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtPasswordMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 270, -1));

        btnAgregarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar Usuario");
        btnAgregarUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel2.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 140, 30));

        lblErrorContraVa1.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorContraVa1.setText("*Debe ingresar una contraseña");
        jPanel2.add(lblErrorContraVa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        lblErrorUsuario.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorUsuario.setText("*Debe ingresar un usuario");
        jPanel2.add(lblErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        lblErrorContraVa.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorContraVa.setText("*Debe ingresar una contraseña");
        jPanel2.add(lblErrorContraVa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        lblErrorContra.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorContra.setText("*La contraseña es diferente");
        jPanel2.add(lblErrorContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 180, -1));

        txtDPI.setBackground(new java.awt.Color(255, 255, 255));
        txtDPI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDPI.setForeground(new java.awt.Color(26, 75, 54));
        txtDPI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDPI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 127, 75));
        jLabel13.setText("DPI*");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-datos-usuarios.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 190));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 970, 190));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eliminar Usuario");
        btnEliminarUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel3.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 127, 75));
        jLabel9.setText("BUSCAR USUARIO");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 127, 75));
        jLabel10.setText("Usuario");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtUsuarioBus.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioBus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsuarioBus.setForeground(new java.awt.Color(26, 75, 54));
        txtUsuarioBus.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuarioBus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtUsuarioBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 270, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 127, 76));
        jLabel11.setText("Contraseña");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        txtPasswordMantConfAc.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMantConfAc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordMantConfAc.setForeground(new java.awt.Color(26, 75, 54));
        txtPasswordMantConfAc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordMantConfAc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtPasswordMantConfAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 127, 76));
        jLabel6.setText("Contraseña");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        txtPasswordMantAc.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMantAc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordMantAc.setForeground(new java.awt.Color(26, 75, 54));
        txtPasswordMantAc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordMantAc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtPasswordMantAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordMantAcActionPerformed(evt);
            }
        });
        jPanel3.add(txtPasswordMantAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 270, -1));
        jPanel3.add(fondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 240));

        btnActualizarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnActualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Actualizar Usuario");
        btnActualizarUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel3.add(btnActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 970, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordMantAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordMantAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMantAcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizarUsuario;
    public javax.swing.JPanel btnAgregarUsuario;
    public javax.swing.JPanel btnEliminarUsuario;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblErrorContra;
    public javax.swing.JLabel lblErrorContraVa;
    public javax.swing.JLabel lblErrorContraVa1;
    public javax.swing.JLabel lblErrorUsuario;
    public javax.swing.JTextField txtDPI;
    public javax.swing.JPasswordField txtPasswordMant;
    public javax.swing.JPasswordField txtPasswordMantAc;
    public javax.swing.JPasswordField txtPasswordMantConf;
    public javax.swing.JPasswordField txtPasswordMantConfAc;
    public javax.swing.JTextField txtUsuarioBus;
    public javax.swing.JTextField txtUsuarioMant;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorUsuario controlador) {
        this.btnAgregarUsuario.addMouseListener(controlador);
        this.btnActualizarUsuario.addMouseListener(controlador);
        this.btnEliminarUsuario.addMouseListener(controlador);
        this.txtPasswordMantConf.getDocument().addDocumentListener(controlador);
        this.txtPasswordMant.getDocument().addDocumentListener(controlador);
        this.txtUsuarioMant.getDocument().addDocumentListener(controlador);
    }
}
