/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorPrueba;
import com.umg.modelos.ModeloPrueba;
import javax.swing.JButton;

/**
 *
 * @author axels
 */
public class VistaPrueba extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrueba
     */
    public VistaPrueba() {
        initComponents();
//        ModeloPrueba modelo = new ModeloPrueba(this);
//        ControladorPrueba controlador = new ControladorPrueba(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnMeReUser = new javax.swing.JPanel();
        btnExpandirMenu = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(0, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(153, 153, 153));
        panelMenu.setPreferredSize(new java.awt.Dimension(50, 720));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMeReUser.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout btnMeReUserLayout = new javax.swing.GroupLayout(btnMeReUser);
        btnMeReUser.setLayout(btnMeReUserLayout);
        btnMeReUserLayout.setHorizontalGroup(
            btnMeReUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        btnMeReUserLayout.setVerticalGroup(
            btnMeReUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelMenu.add(btnMeReUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        btnExpandirMenu.setBackground(new java.awt.Color(153, 255, 255));
        btnExpandirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExpandirMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/menuIcono.png"))); // NOI18N
        btnExpandirMenu.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        btnExpandirMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        panelMenu.add(btnExpandirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        PanelPrincipal.add(panelMenu, java.awt.BorderLayout.LINE_START);

        contenedor.setBackground(new java.awt.Color(204, 204, 204));
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.LINE_AXIS));
        PanelPrincipal.add(contenedor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    public javax.swing.JPanel btnExpandirMenu;
    public javax.swing.JPanel btnMeReUser;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

//    public void setControlador(ControladorPrueba controlador){
//        btnRegresar.addActionListener(controlador);
//    }
}
