/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.vistas;

import com.digitalpersona.uareu.UareUException;
import com.digitalpersona.uareu.UareUGlobal;
import com.umg.controlador.ControladorLogin;
import com.umg.modelos.ModeloLogin;
import com.umg.modelos.ModeloMenu;
import javax.swing.JPanel;

/**
 *
 * @author sebas
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    public VistaPrincipal() {
        initComponents();
        this.setTitle("Mantenimineto Empleados");
        setSize(1280, 720);
        this.setLocationRelativeTo(null);
        
        ModeloLogin modelo = new ModeloLogin();
        VistaLogin vista = new VistaLogin();
        new ControladorLogin(modelo, vista, this);
        this.cambiarPanel(vista);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cerrarAplicacion();
            }
        });
    }

    public void cambiarPanel(JPanel nuevoPanel){
        contenedor.removeAll();
        contenedor.add(nuevoPanel);
        contenedor.revalidate();
        contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 760));
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 760));

        contenedor.setMinimumSize(new java.awt.Dimension(1280, 720));
        contenedor.setPreferredSize(new java.awt.Dimension(1280, 720));
        contenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel contenedor;
    // End of variables declaration//GEN-END:variables

    private void cerrarAplicacion() {
        try {
            UareUGlobal.DestroyReaderCollection();
            System.out.println("Colección de lectores destruida correctamente.");
        } catch (UareUException e) {
            //MessageBox.DpError("UareUGlobal.DestroyReaderCollection()", e);
            System.out.println("UareUGlobal.DestroyReaderCollection() error: " + e.getMessage());
        }
        System.exit(0); // Finalmente, cierra la aplicación
    }
}
