/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorUsuario;
import com.umg.modelos.ModeloUsuario;

/**
 *
 * @author axels
 */
public class VistaMantenimientoUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form VistaMantenimeintoUsuarios
     */
    public VistaMantenimientoUsuarios() {
        initComponents();
        ModeloUsuario modelo = new ModeloUsuario(this);
        ControladorUsuario controlador = new ControladorUsuario(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuarioMant = new javax.swing.JTextField();
        txtPasswordMant = new javax.swing.JPasswordField();
        btnAgregarUsuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnActualizarUsuario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEliminarUsuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        fondo.setBackground(new java.awt.Color(240, 253, 244));
        fondo.setMinimumSize(new java.awt.Dimension(1230, 720));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 127, 75));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Usuarios");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 400, 60));

        jPanel2.setBackground(new java.awt.Color(240, 253, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 127, 75));
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 127, 76));
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        txtUsuarioMant.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioMant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsuarioMant.setForeground(new java.awt.Color(26, 75, 54));
        txtUsuarioMant.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuarioMant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtUsuarioMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 270, -1));

        txtPasswordMant.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordMant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPasswordMant.setForeground(new java.awt.Color(26, 75, 54));
        txtPasswordMant.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordMant.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtPasswordMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 270, -1));

        btnAgregarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar Usuario");
        btnAgregarUsuario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel2.add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 140, 30));

        btnActualizarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnActualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Actualizar Usuario");
        btnActualizarUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel2.add(btnActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-datos-usuarios.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 130));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 970, 130));

        jPanel3.setBackground(new java.awt.Color(240, 253, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarUsuario.setBackground(new java.awt.Color(0, 127, 75));
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Eliminar Usuario");
        btnEliminarUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jPanel3.add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 140, 30));

        tblUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblUsuarios.setForeground(new java.awt.Color(26, 75, 54));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "USUARIO"
            }
        ));
        jScrollPane2.setViewportView(tblUsuarios);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 890, 270));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/img-tabla-usuarios.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 390));

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 970, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizarUsuario;
    public javax.swing.JPanel btnAgregarUsuario;
    public javax.swing.JPanel btnEliminarUsuario;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblUsuarios;
    public javax.swing.JPasswordField txtPasswordMant;
    public javax.swing.JTextField txtUsuarioMant;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorUsuario controlador) {
        this.btnAgregarUsuario.addMouseListener(controlador);
        this.btnActualizarUsuario.addMouseListener(controlador);
        this.btnEliminarUsuario.addMouseListener(controlador);
    }
}
