/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.vistas;

import com.umg.controlador.ControladorMenu;
import com.umg.modelos.ModeloMenu;
import javax.swing.JButton;

/**
 *
 * @author axels
 */
public class VistaMenu extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrueba
     */
    public VistaMenu() {
        initComponents();
        ControladorMenu controladorMenu = new ControladorMenu();
        controladorMenu.animacionLabel(lblTitulo1);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnMeReUser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnExpandirMenu = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMeMoEmple = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        btnGestionUsuarios = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRegresarLogin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnActuEmpleado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMantePuestos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEliminarEmpleado = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        panelFondoMenu = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(0, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(0, 127, 75));
        panelMenu.setPreferredSize(new java.awt.Dimension(50, 720));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMeReUser.setBackground(new java.awt.Color(0, 127, 75));
        btnMeReUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeReUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar Empleado");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnMeReUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/empleadosIcono.png"))); // NOI18N
        btnMeReUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnMeReUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        btnExpandirMenu.setBackground(new java.awt.Color(0, 127, 75));
        btnExpandirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExpandirMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/menuIcono.png"))); // NOI18N
        btnExpandirMenu.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnExpandirMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        panelMenu.add(btnExpandirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        btnMeMoEmple.setBackground(new java.awt.Color(0, 127, 75));
        btnMeMoEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeMoEmple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mostrar Empleados");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnMeMoEmple.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/busempleadosIcono.png"))); // NOI18N
        btnMeMoEmple.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnMeMoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        btnGestionUsuarios.setBackground(new java.awt.Color(0, 127, 75));
        btnGestionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestión Usuarios");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnGestionUsuarios.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/usuariosIcono.png"))); // NOI18N
        btnGestionUsuarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        jPanel4.setBackground(new java.awt.Color(0, 127, 75));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        panelMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 270));

        btnRegresarLogin.setBackground(new java.awt.Color(0, 127, 75));
        btnRegresarLogin.setForeground(new java.awt.Color(0, 127, 75));
        btnRegresarLogin.setToolTipText("");
        btnRegresarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Salir");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnRegresarLogin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/saliricono.png"))); // NOI18N
        btnRegresarLogin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnRegresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 200, 50));

        btnActuEmpleado.setBackground(new java.awt.Color(0, 127, 75));
        btnActuEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActuEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Actualizar Empleado");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnActuEmpleado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/empleadoactualizaricono.png"))); // NOI18N
        btnActuEmpleado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnActuEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        btnMantePuestos.setBackground(new java.awt.Color(0, 127, 75));
        btnMantePuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantePuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gestión de Puestos");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnMantePuestos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/puestoIcono.png"))); // NOI18N
        btnMantePuestos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnMantePuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        btnEliminarEmpleado.setBackground(new java.awt.Color(0, 127, 75));
        btnEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Eliminar Empleado");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(0, 127, 75)));
        btnEliminarEmpleado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/umg/imagenes/eliminarEmpleadoIcono.png"))); // NOI18N
        btnEliminarEmpleado.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenu.add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        PanelPrincipal.add(panelMenu, java.awt.BorderLayout.LINE_START);

        contenedor.setBackground(new java.awt.Color(240, 253, 244));
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.LINE_AXIS));

        panelFondoMenu.setBackground(new java.awt.Color(240, 253, 244));
        panelFondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 127, 75));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Bienvenido");
        panelFondoMenu.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1220, 710));

        contenedor.add(panelFondoMenu);

        PanelPrincipal.add(contenedor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    public javax.swing.JPanel btnActuEmpleado;
    public javax.swing.JPanel btnEliminarEmpleado;
    public javax.swing.JPanel btnExpandirMenu;
    public javax.swing.JPanel btnGestionUsuarios;
    public javax.swing.JPanel btnMantePuestos;
    public javax.swing.JPanel btnMeMoEmple;
    public javax.swing.JPanel btnMeReUser;
    public javax.swing.JPanel btnRegresarLogin;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblImagen;
    public javax.swing.JLabel lblTitulo1;
    public javax.swing.JPanel panelFondoMenu;
    public javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

//    public void setControlador(ControladorMenu controlador){
//        btnRegresar.addActionListener(controlador);
//    }
}
